### ISSUE TITLE
Welcome! And migration from Google Doc to this repo

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/bids-2-devel#1]
Welcome to this new repository everybody!

For context, please see the messages in the BrainHack Mattermost starting approximately with [this message by @tsalo ](https://mattermost.brainhack.org/brainhack/pl/ooomx4kx3p8t5k1btfid8izc4o).

Next steps:

1. [x] migrate all existing suggestions and discussions
1. [x] render the BIDS 2.0 google doc "view only"
1. [x] label the new issues

We need to migrate all suggestions / comments and preferably also discussions from the [BIDS 2.0 google doc](https://docs.google.com/document/d/1LEgsMiisGDe1Gv-hBp1EcLmoz7AlKj6VYULUgDD3Zdw/edit?ts=5ec29f62#) to this repository.

- Who wants to help?
- How should we proceed?
- What's important to keep in mind?

**Comment by tsalo** [comment]
I'm happy to help! It seems pretty straightforward to copy over the contents of the Doc, but the big problem, as far as I can tell, is attributing ideas to individuals. Most of the suggestions for ideas have already been accepted, so it would be pretty difficult to go through the history and track down each person who contributed an idea, and then figure out their GitHub handle, if they even have an account.

I recommend the following: 
1. We start opening issues for recommendations
2. When we know who came up with the idea, we tag them. Otherwise, we just let it go. People can always tag themselves later, if need be.
3. When there are comments, we add them as new comments on the issue. When we know the GitHub handle of the commenter, we tag them in the comment (e.g., "@tsalo said: "). Otherwise, we use the person's name. We can always edit the comments to replace names with handles later.

From there, we can use Project boards or labels to collect the suggestions into more manageable groups. I think the same labels as `bids-specification` should be good to start.

**Comment by tsalo** [comment]
What about an issue template with the following?

```
# content of suggestion

Original authors:
```

We leave "original authors" empty until we know the authors, then we can edit the issue with handles or names as needed. The "content of suggestion" would be the text from the Doc, with the issue title obviously being the title of the suggestion.

**Comment by tsalo** [comment]
Here's a list of the issues we need to open, with a first attempt at attribution:

- Remove RepetitionTime Metadata Field
- Change FLASH for non-proprietary name
- Add magnetization transfer
- Allowing hyphens in filename key values: @\bthirion
- Keep the filenames short: @\ccraddock
- Allow tabs in .bvec/.bval
- Exchange “-” with “_” and vice versa: @\andrebeu
- Multi-site/center studies: @\jpellman
- Revert to one directory per scan
- Extended BIDS for animals
- Remove inheritance rule: @\ccraddock
- Add a compulsory header to every JSON file: @\ccraddock
- Allow expressing parameters in different units: @\ccraddock
- Make key/value pair: _run-XX suffix mandatory
- File format for raw data
- Replacing “task” with “trial”: @\TheChymera
- Support for multiple 3D files in addition to 4D filed for bold: @\gllmflndn
- Replace `_scans.tsv` with `_recordings.tsv`
- One directory per modality
- Store date/time information in the JSON sidecar instead of _scans.tsv file: @\chrisgorgo
- Make capitalization of suffixes consistent: @\jbpoline
- Drop sidecar JSON files and store all metadata in the header
- Use IETF RFC 2119 keywords to indicate requirement levels
- Use Augmented Backus–Naur form instead of definition templates
- Harmonizing sequence/contrast names: Martijn Mulder (not sure about GitHub handle)
- Addition of scan length in the JSON sidecar: @\tyarkoni
- Consider replacing data dictionaries with Table Schema
- Consider replacing TSV files with a fileformat that supports built in metadata
- Change RepetitionTime definition to the same one as DICOM field 0018,0080: @\mharms
- Enforce TE ordering for multi-echo fMRI data: @\emdupre
- Allowed characters in labels/keys
- Alternative location for raw data
- MINOR: Replace “units” with “unit” in channels.tsv
- Homogenize “Subject” Nomenclature: @\TheChymera
- N/A vs NaN for missing values: @\CPLambert
- Phenotypes
- Deprecate phase, phase1, phase2, phasediff, magnitude1, magnitude2 suffixes in favor of part and echo entities: @\tsalo
- Move and Rename IntendedFor field from fieldmap to functional image: @\akimbler

**Comment by sappelhoff** [comment]
Thanks for the initiative and energy @tsalo - I just gave you maintainer permissions for this repository so that you can create project boards as you see fit. I think approach is reasonable and we can take it step by step from here

**Comment by tsalo** [comment]
I've opened the issues now, so I think the next step should be to label them. Many of these issues are >=3 years old, and at least some of them might have already been incorporated into the specification (e.g., #6 and #18 are both part of BEP-001, I believe).

I'm leaning toward the following labels:

- `1.0-compatible`: These can be proposed for the specification in its current form. We will probably link these to BIDS 1.0 issues and then close them.
- `folder-structure`: Proposals to reorganize files in the specification.
- `characters`: Proposals to change accepted characters throughout the specification.
- `deprecation`: Proposals to remove entities, suffixes, etc. that are currently implemented.
- `common-principles`: Proposals to change common principles (e.g., remove inheritance rule, add required header to JSON files).
- `entities`: Changes to entities.
- `metadata`: Changes to metadata fields/files.
- `suffixes`: Changes to suffixes.
- `impact: [low|medium|high]`

**Comment by sappelhoff** [comment]
Done, and the labels sound good, feel free to go ahead and create them. I think we are ready to render the Gdoc "view only" now, WDYT?

**Comment by tsalo** [comment]
I just had to add links for the last two issues, but now it's good to lock.

**Comment by jbteves** [comment]
How should we indicate approval/disapproval on various items? And is commentary limited to existing BIDS community members?

**Comment by tsalo** [comment]
I don't think commentary should be limited to BIDS contributors (although being familiar with the standard is important), and I think :+1: and :-1: should be good for simple approval/disapproval, with comments if you have a more nuanced take.

**Comment by sappelhoff** [comment]
> How should we indicate approval/disapproval on various items?

I think a standalone :+1: is fine, but :-1: SHOULD be accompanied with a reason.


> And is commentary limited to existing BIDS community members?

We are an open community, there is no "application form" or something like it :-) just comment.

**Comment by sappelhoff** [comment]
migration is done, closing this.
